name: generate build number

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate build number
        id: build-number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}     
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - name: Print new output value
        run: echo "Build number is ${{ steps.build-number.outputs.build_number }}"
