name: update misrecognition table

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: update text
        run: 
          echo "text" >> ./change_and_commit/test.txt
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2
        with:
          files: |
            voiceReplaceTable.js
      - name: diff file count
        if: steps.changed-files.outputs.only_modified
        id: diff-file-count
        run: git diff
      #- name: commit files
      #  if: steps.diff-file-count.outputs.count > 0
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add ./src
      #    git commit -m "auto format"
      #- name: Push changes
      #  if: steps.diff-file-count.outputs.count > 0
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: ${{ github.ref }}
