name: Hello
on: push
jobs:
    hello_world_job:
        runs-on: ubuntu-latest      # 最新のUbuntu環境で実行
        env:
            PASS: PASSVALUE
        steps:                      # ステップ
            - run: |
                echo "# Title: Hello World" >> ${GITHUB_STEP_SUMMARY}
                echo "Hello World!" >> ${GITHUB_STEP_SUMMARY}
                echo "This is a test of GitHub Actions." >> ${GITHUB_STEP_SUMMARY}