name: Hello
on: push
jobs:
    hello_world_job:
        runs-on: ubuntu-latest      # 最新のUbuntu環境で実行
        env:
            PASS: PASSVALUE
        steps:                      # ステップ
            - uses: actions/github-script@v8
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const output = `\n## Hello World!\n
                    This is a test of GitHub Actions.\n
                    *Pushed by: @${{ github.sha }}, Action: \`${{ github.event_name }}\`*`;
                    await core.summary.addHeading("Script Sample").addRaw(output).write()
            - run: |
                echo "Hello, World!" # Hello, World! を出力
                echo ::debug::This is a debug message.