name: Hello
on: push
jobs:
    hello_world_job:
        runs-on: ubuntu-latest      # 最新のUbuntu環境で実行
        env:
            PASS: PASSVALUE
        steps:                      # ステップ
            - uses: actions/github-script@v8
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                    const output = `## Hello World!
                    This is a test of GitHub Actions.
                    *Pushed by: @${{ github.sha }}, Action: \`${{ github.event_name }}\`*`;

                    github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                    })
                    await core.summary.addHeading("Script Sample").addRaw(output).write()